import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const tableColumns = {
  seasons: [
    "year",
    "name",
    "categories",
    "rosterSpots",
    "startDate",
    "endDate",
    "isActive",
    "usesLegacyTies",
    "signingEndDate",
    "createdAt",
    "updatedAt",
  ],
  conferences: ["name", "logoUrl", "abbr", "createdAt", "updatedAt"],
  franchises: [
    "ownerId",
    "name",
    "abbr",
    "logoUrl",
    "confId",
    "isActive",
    "createdAt",
    "updatedAt",
  ],
  teams: [
    "seasonId",
    "franchiseId",
    "yahooId",
    "confId",
    "createdAt",
    "updatedAt",
  ],
  owners: [
    "firstName",
    "lastName",
    "nickName",
    "email",
    "owing",
    "isActive",
    "createdAt",
    "updatedAt",
  ],
  players: [
    "yahooId",
    "firstName",
    "lastName",
    "fullName",
    "nhlPos",
    "posGroup",
    "nhlTeam",
    "isActive",
    "isSignable",
    "isResignable",
    "preDraftRk",
    "seasonRk",
    "seasonRating",
    "overallRk",
    "overallRating",
    "salary",
    "age",
    "birthday",
    "country",
    "handedness",
    "jerseyNum",
    "weight",
    "height",
    "lineupPos",
    "gshlTeamId",
    "nhlContractStatus",
    "nhlContractLength",
    "nhlCapHit",
    "nhlClauses",
    "nhlStartYear",
    "nhlSigningStatus",
    "nhlExpiryYear",
    "nhlExpiryStatus",
    "createdAt",
    "updatedAt",
    "nhlApiId",
  ],
  contracts: [
    "playerId",
    "ownerId",
    "seasonId",
    "contractType",
    "contractLength",
    "contractSalary",
    "signingDate",
    "startDate",
    "signingStatus",
    "expiryStatus",
    "expiryDate",
    "capHit",
    "capHitEndDate",
    "createdAt",
    "updatedAt",
  ],
  weeks: [
    "seasonId",
    "weekNum",
    "weekType",
    "gameDays",
    "startDate",
    "endDate",
    "isActive",
    "isPlayoffs",
    "createdAt",
    "updatedAt",
  ],
  matchups: [
    "seasonId",
    "weekId",
    "homeTeamId",
    "awayTeamId",
    "gameType",
    "homeRank",
    "awayRank",
    "homeScore",
    "awayScore",
    "homeWin",
    "awayWin",
    "tie",
    "isComplete",
    "rating",
    "ratingPre",
    "ratingRealized",
    "ratingCompetitive",
    "ratingImportance",
    "ratingRosterStrength",
    "createdAt",
    "updatedAt",
  ],
  events: [
    "seasonId",
    "name",
    "description",
    "date",
    "type",
    "createdAt",
    "updatedAt",
  ],
  awards: [
    "seasonId",
    "winnerId",
    "nomineeIds",
    "award",
    "createdAt",
    "updatedAt",
  ],
  draftPicks: [
    "seasonId",
    "gshlTeamId",
    "originalTeamId",
    "round",
    "pick",
    "playerId",
    "isTraded",
    "isSigning",
    "createdAt",
    "updatedAt",
  ],
  nhlTeams: [
    "name",
    "abbr",
    "fullName",
    "abbreviation",
    "logoUrl",
    "createdAt",
    "updatedAt",
  ],
  playerDayStatLines: [
    "seasonId",
    "gshlTeamId",
    "playerId",
    "weekId",
    "date",
    "nhlPos",
    "posGroup",
    "nhlTeam",
    "dailyPos",
    "bestPos",
    "fullPos",
    "opp",
    "score",
    "GP",
    "MG",
    "IR",
    "IRplus",
    "GS",
    "G",
    "A",
    "P",
    "PM",
    "PIM",
    "PPP",
    "SOG",
    "HIT",
    "BLK",
    "W",
    "GA",
    "GAA",
    "SV",
    "SA",
    "SVP",
    "SO",
    "TOI",
    "Rating",
    "ADD",
    "MS",
    "BS",
    "createdAt",
    "updatedAt",
  ],
  playerWeekStatLines: [
    "seasonId",
    "gshlTeamId",
    "playerId",
    "weekId",
    "nhlPos",
    "posGroup",
    "nhlTeam",
    "days",
    "GP",
    "MG",
    "IR",
    "IRplus",
    "GS",
    "G",
    "A",
    "P",
    "PM",
    "PIM",
    "PPP",
    "SOG",
    "HIT",
    "BLK",
    "W",
    "GA",
    "GAA",
    "SV",
    "SA",
    "SVP",
    "SO",
    "TOI",
    "Rating",
    "ADD",
    "MS",
    "BS",
    "createdAt",
    "updatedAt",
  ],
  playerSplitStatLines: [],
  playerTotalStatLines: ["gshlTeamIds"],
  playerCareerSplitStatLines: [],
  playerCareerTotalStatLines: ["gshlTeamIds"],
  playerNhlStatLines: [
    "seasonId",
    "playerId",
    "nhlPos",
    "posGroup",
    "nhlTeam",
    "age",
  ],
  teamDayStatLines: ["seasonId", "gshlTeamId", "weekId", "date"],
  teamWeekStatLines: [
    "seasonId",
    "gshlTeamId",
    "weekId",
    "powerRating",
    "powerRk",
  ],
  teamSeasonStatLines: [
    "seasonId",
    "seasonType",
    "gshlTeamId",
    "streak",
    "powerRk",
  ],
} as const;

const statColumns = [
  "days",
  "GP",
  "MG",
  "IR",
  "IRplus",
  "GS",
  "G",
  "A",
  "P",
  "PM",
  "PIM",
  "PPP",
  "SOG",
  "HIT",
  "BLK",
  "W",
  "GA",
  "GAA",
  "SV",
  "SA",
  "SVP",
  "SO",
  "TOI",
  "Rating",
  "ADD",
  "MS",
  "BS",
  "createdAt",
  "updatedAt",
] as const;

function table(fields: readonly string[]) {
  const shape = Object.fromEntries(
    Array.from(new Set(["legacyId", ...fields])).map((field) => [
      field,
      v.optional(v.any()),
    ]),
  );

  return defineTable(shape).index("by_legacyId", ["legacyId"]);
}

export default defineSchema({
  seasons: table(tableColumns.seasons),
  conferences: table(tableColumns.conferences),
  franchises: table(tableColumns.franchises),
  teams: table(tableColumns.teams),
  owners: table(tableColumns.owners),
  players: table(tableColumns.players),
  contracts: table(tableColumns.contracts),
  weeks: table(tableColumns.weeks),
  matchups: table(tableColumns.matchups),
  events: table(tableColumns.events),
  awards: table(tableColumns.awards),
  draftPicks: table(tableColumns.draftPicks),
  nhlTeams: table(tableColumns.nhlTeams),
  playerDayStatLines: table(tableColumns.playerDayStatLines),
  playerWeekStatLines: table(tableColumns.playerWeekStatLines),
  playerSplitStatLines: table([
    "seasonId",
    "gshlTeamId",
    "playerId",
    "nhlPos",
    "posGroup",
    "nhlTeam",
    "seasonType",
    ...statColumns,
  ]),
  playerTotalStatLines: table([
    "seasonId",
    "gshlTeamIds",
    "playerId",
    "nhlPos",
    "posGroup",
    "nhlTeam",
    "seasonType",
    ...statColumns,
  ]),
  playerCareerSplitStatLines: table([
    "gshlTeamId",
    "playerId",
    "nhlPos",
    "posGroup",
    "nhlTeam",
    "seasonType",
    ...statColumns,
  ]),
  playerCareerTotalStatLines: table([
    "gshlTeamIds",
    "playerId",
    "nhlPos",
    "posGroup",
    "nhlTeam",
    "seasonType",
    ...statColumns,
  ]),
  playerNhlStatLines: table([
    ...tableColumns.playerNhlStatLines,
    "GP",
    "G",
    "A",
    "P",
    "PM",
    "PIM",
    "PPP",
    "SOG",
    "HIT",
    "BLK",
    "W",
    "GA",
    "GAA",
    "SV",
    "SA",
    "SVP",
    "SO",
    "QS",
    "RBS",
    "TOI",
    "seasonRating",
    "overallRating",
    "salary",
    "createdAt",
    "updatedAt",
  ]),
  teamDayStatLines: table([...tableColumns.teamDayStatLines, ...statColumns]),
  teamWeekStatLines: table([
    ...tableColumns.teamWeekStatLines,
    ...statColumns,
    "powerElo",
    "powerEloPre",
    "powerEloPost",
    "powerEloDelta",
    "powerEloExpected",
    "powerEloK",
    "powerStatScore",
    "powerStatEwma",
    "powerTalent",
    "powerHistoryPrior",
    "powerComposite",
  ]),
  teamSeasonStatLines: table([
    ...tableColumns.teamSeasonStatLines,
    ...statColumns,
    "teamW",
    "teamHW",
    "teamHL",
    "teamL",
    "teamT",
    "teamCCW",
    "teamCCHW",
    "teamCCHL",
    "teamCCL",
    "teamCCT",
    "overallRk",
    "conferenceRk",
    "wildcardRk",
    "playersUsed",
    "hartRating",
    "hartRk",
    "norrisRating",
    "norrisRk",
    "vezinaRating",
    "vezinaRk",
    "calderRating",
    "calderRk",
    "jackAdamsRating",
    "jackAdamsRk",
    "GMOYRating",
    "GMOYRk",
  ]),
});
