// Configuration for mapping database models to Google Sheets

// Multi-workbook configuration matching your Apps Script setup
export const WORKBOOKS = {
  GENERAL: "1I6kmnnL6rSAWLOG12Ixr89g4W-ZQ0weGbfETKDTrvH8",
  PLAYERDAYS: "1aFCl4Zep_t09emxMf8aesAvCYxQGrbmcNEshjRD_J_w",
  PLAYERSTATS: "1qkyxmx8gC-xs8niDrmlB9Jv6qXhRmAWjFCq8ECEr-Cg",
  TEAMSTATS: "1X2pvw18aYEekdNApyJMqijOZL1Bl0e3Azlkg-eb2X54",
};

// Model to workbook mapping
export const MODEL_TO_WORKBOOK: Record<string, keyof typeof WORKBOOKS> = {
  // GENERAL workbook
  Season: "GENERAL",
  Conference: "GENERAL",
  Week: "GENERAL",
  Matchup: "GENERAL",
  Event: "GENERAL",
  Owner: "GENERAL",
  Franchise: "GENERAL",
  Team: "GENERAL",
  Player: "GENERAL",
  Contract: "GENERAL",
  Awards: "GENERAL",
  DraftPick: "GENERAL",
  nhlTeam: "GENERAL", // legacy/lowercase model key
  NHLTeam: "GENERAL", // alias for actual sheet named 'NHLTeam'

  // PLAYERDAYS workbook
  PlayerDayStatLine: "PLAYERDAYS",
  TeamDayStatLine: "TEAMSTATS",
  TeamWeekStatLine: "TEAMSTATS",
  TeamSeasonStatLine: "TEAMSTATS",
};

export const SHEETS_CONFIG = {
  // Sheet names for each model
  SHEETS: {
    Season: "Season",
    Conference: "Conference",
    Franchise: "Franchise",
    Team: "Team",
    Player: "Player",
    Contract: "Contract",
    Week: "Week",
    PlayerDayStatLine: "PlayerDayStatLine",
    PlayerWeekStatLine: "PlayerWeekStatLine",
    PlayerSplitStatLine: "PlayerSplitStatLine",
    PlayerTotalStatLine: "PlayerTotalStatLine",
    PlayerNHLStatLine: "PlayerNHLStatLine",
    TeamDayStatLine: "TeamDayStatLine",
    TeamWeekStatLine: "TeamWeekStatLine",
    TeamSeasonStatLine: "TeamSeasonStatLine",
    Event: "Event",
    Matchup: "Matchup",
    Owner: "Owner",
    Awards: "Awards",
    DraftPick: "DraftPick",
    nhlTeam: "nhlTeam", // legacy
    NHLTeam: "NHLTeam", // actual sheet name as provided
    // ArchivedSkaterDayStatLine: "ArchivedSkaterDayStatLine", // Disabled for performance
    // ArchivedGoalieDayStatLine: "ArchivedGoalieDayStatLine", // Disabled for performance
  },

  // Column mappings for each model (these match our database schema)
  COLUMNS: {
    NHLTeam: [
      "id",
      "fullName",
      "abbreviation",
      "logoUrl",
      "createdAt",
      "updatedAt",
    ],
    PlayerDayStatLine: [
      "id",
      "seasonId",
      "gshlTeamId",
      "playerId",
      "weekId",
      "date",
      "nhlPos",
      "posGroup",
      "nhlTeam",
      "dailyPos",
      "bestPos",
      "fullPos",
      "opp",
      "score",
      "GP",
      "MG",
      "IR",
      "IRplus",
      "GS",
      "G",
      "A",
      "P",
      "PM",
      "PIM",
      "PPP",
      "SOG",
      "HIT",
      "BLK",
      "W",
      "GA",
      "GAA",
      "SV",
      "SA",
      "SVP",
      "SO",
      "TOI",
      "Rating",
      "ADD",
      "MS",
      "BS",
      "createdAt",
      "updatedAt",
    ],
    PlayerWeekStatLine: [
      "id",
      "seasonId",
      "gshlTeamId",
      "playerId",
      "weekId",
      "nhlPos",
      "posGroup",
      "nhlTeam",
      "days",
      "GP",
      "MG",
      "IR",
      "IRPlus",
      "GS",
      "G",
      "A",
      "P",
      "PM",
      "PIM",
      "PPP",
      "SOG",
      "HIT",
      "BLK",
      "W",
      "GA",
      "GAA",
      "SV",
      "SA",
      "SVP",
      "SO",
      "TOI",
      "Rating",
      "ADD",
      "MS",
      "BS",
      "createdAt",
      "updatedAt",
    ],
    Season: [
      "id",
      "year",
      "name",
      "categories",
      "rosterSpots",
      "startDate",
      "endDate",
      "isActive",
      "signingEndDate",
      "createdAt",
      "updatedAt",
    ],
    Team: ["id", "seasonId", "franchiseId", "confId", "createdAt", "updatedAt"],
    Player: [
      "id",
      "firstName",
      "lastName",
      "fullName",
      "nhlPos",
      "posGroup",
      "nhlTeam",
      "isActive",
      "isSignable",
      "isResignable",
      "seasonRk",
      "seasonRating",
      "overallRk",
      "overallRating",
      "salary",
      "age",
      "birthday",
      "country",
      "handedness",
      "jerseyNum",
      "weight",
      "height",
      "lineupPos",
      "gshlTeamId",
      "createdAt",
      "updatedAt",
    ],
    Week: [
      "id",
      "seasonId",
      "weekNum",
      "weekType",
      "gameDays",
      "startDate",
      "endDate",
      "isActive",
      "isPlayoffs",
      "createdAt",
      "updatedAt",
    ],
    Conference: ["id", "name", "logoUrl", "abbr", "createdAt", "updatedAt"],
    Owner: [
      "id",
      "firstName",
      "lastName",
      "nickName",
      "email",
      "owing",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    Contract: [
      "id",
      "playerId",
      "signingFranchiseId",
      "currentFranchiseId",
      "seasonId",
      "contractType",
      "contractLength",
      "contractSalary",
      "signingDate",
      "startDate",
      "signingStatus",
      "expiryStatus",
      "expiryDate",
      "capHit",
      "capHitEndDate",
      "createdAt",
      "updatedAt",
    ],
    Franchise: [
      "id",
      "ownerId",
      "name",
      "abbr",
      "logoUrl",
      "confId",
      "isActive",
      "createdAt",
      "updatedAt",
    ],
    PlayerSplitStatLine: [
      "id",
      "seasonId",
      "gshlTeamId",
      "playerId",
      "nhlPos",
      "posGroup",
      "nhlTeam",
      "seasonType",
      "days",
      "GP",
      "MG",
      "IR",
      "IRplus",
      "GS",
      "G",
      "A",
      "P",
      "PM",
      "PIM",
      "PPP",
      "SOG",
      "HIT",
      "BLK",
      "W",
      "GA",
      "GAA",
      "SV",
      "SA",
      "SVP",
      "SO",
      "TOI",
      "Rating",
      "ADD",
      "MS",
      "BS",
      "createdAt",
      "updatedAt",
    ],
    PlayerTotalStatLine: [
      "id",
      "seasonId",
      "gshlTeamIds",
      "playerId",
      "nhlPos",
      "posGroup",
      "nhlTeam",
      "seasonType",
      "days",
      "GP",
      "MG",
      "IR",
      "IRplus",
      "GS",
      "G",
      "A",
      "P",
      "PM",
      "PIM",
      "PPP",
      "SOG",
      "HIT",
      "BLK",
      "W",
      "GA",
      "GAA",
      "SV",
      "SA",
      "SVP",
      "SO",
      "TOI",
      "Rating",
      "ADD",
      "MS",
      "BS",
      "createdAt",
      "updatedAt",
    ],
    PlayerNHLStatLine: [
      "id",
      "seasonId",
      "playerId",
      "nhlPos",
      "posGroup",
      "nhlTeam",
      "age",
      "GP",
      "G",
      "A",
      "P",
      "PM",
      "PIM",
      "PPP",
      "SOG",
      "HIT",
      "BLK",
      "W",
      "GA",
      "GAA",
      "SV",
      "SA",
      "SVP",
      "SO",
      "QS",
      "RBS",
      "TOI",
      "seasonRating",
      "overallRating",
      "salary",
      "createdAt",
      "updatedAt",
    ],
    TeamDayStatLine: [
      "id",
      "seasonId",
      "gshlTeamId",
      "weekId",
      "date",
      "GP",
      "MG",
      "IR",
      "IRplus",
      "GS",
      "G",
      "A",
      "P",
      "PM",
      "PIM",
      "PPP",
      "SOG",
      "HIT",
      "BLK",
      "W",
      "GA",
      "GAA",
      "SV",
      "SA",
      "SVP",
      "SO",
      "TOI",
      "Rating",
      "ADD",
      "MS",
      "BS",
      "createdAt",
      "updatedAt",
    ],
    TeamWeekStatLine: [
      "id",
      "seasonId",
      "gshlTeamId",
      "weekId",
      "days",
      "GP",
      "MG",
      "IR",
      "IRplus",
      "GS",
      "G",
      "A",
      "P",
      "PM",
      "PIM",
      "PPP",
      "SOG",
      "HIT",
      "BLK",
      "W",
      "GA",
      "GAA",
      "SV",
      "SA",
      "SVP",
      "SO",
      "TOI",
      "Rating",
      "yearToDateRating",
      "powerRating",
      "powerRk",
      "ADD",
      "MS",
      "BS",
      "createdAt",
      "updatedAt",
    ],
    TeamSeasonStatLine: [
      "id",
      "seasonId",
      "seasonType",
      "gshlTeamId",
      "days",
      "GP",
      "MG",
      "IR",
      "IRplus",
      "GS",
      "G",
      "A",
      "P",
      "PM",
      "PIM",
      "PPP",
      "SOG",
      "HIT",
      "BLK",
      "W",
      "GA",
      "GAA",
      "SV",
      "SA",
      "SVP",
      "SO",
      "TOI",
      "Rating",
      "ADD",
      "MS",
      "BS",
      "streak",
      "powerRk",
      "powerRating",
      "prevPowerRk",
      "prevPowerRating",
      "teamW",
      "teamHW",
      "teamHL",
      "teamL",
      "overallRk",
      "conferenceRk",
      "wildcardRk",
      "losersTournRk",
      "playersUsed",
      "norrisRating",
      "norrisRk",
      "vezinaRating",
      "vezinaRk",
      "calderRating",
      "calderRk",
      "jackAdamsRating",
      "jackAdamsRk",
      "GMOYRating",
      "GMOYRk",
      "createdAt",
      "updatedAt",
    ],
    Event: [
      "id",
      "seasonId",
      "name",
      "description",
      "date",
      "type",
      "createdAt",
      "updatedAt",
    ],
    Matchup: [
      "id",
      "seasonId",
      "weekId",
      "homeTeamId",
      "awayTeamId",
      "gameType",
      "homeRank",
      "awayRank",
      "homeScore",
      "awayScore",
      "homeWin",
      "awayWin",
      "tie",
      "isCompleted",
      "rating",
      "createdAt",
      "updatedAt",
    ],
    Awards: [
      "id",
      "seasonId",
      "winnerId",
      "nomineeIds",
      "award",
      "createdAt",
      "updatedAt",
    ],
    DraftPick: [
      "id",
      "seasonId",
      "gshlTeamId",
      "originalTeamId",
      "round",
      "pick",
      "playerId",
      "isTraded",
      "createdAt",
      "updatedAt",
    ],
    nhlTeam: [
      "id",
      "fullName",
      "abbreviation",
      "logoUrl",
      "createdAt",
      "updatedAt",
    ],
    // ArchivedSkaterDayStatLine: [  // Disabled for performance
    //   "id",
    //   "originalId",
    //   "seasonId",
    //   "gshlTeamId",
    //   "playerId",
    //   "weekId",
    //   "date",
    //   "nhlPos",
    //   "posGroup",
    //   "nhlTeam",
    //   "fullPos",
    //   "bestPos",
    //   "dailyPos",
    //   "opp",
    //   "score",
    //   "IR",
    //   "IRplus",
    //   "GP",
    //   "MG",
    //   "GS",
    //   "G",
    //   "A",
    //   "P",
    //   "PM",
    //   "PIM",
    //   "PPP",
    //   "SOG",
    //   "HIT",
    //   "BLK",
    //   "TOI",
    //   "ADD",
    //   "Rating",
    //   "MS",
    //   "BS",
    //   "archivedDate",
    //   "archiveReason",
    //   "originalCreatedAt",
    //   "originalUpdatedAt",
    //   "createdAt",    //   "updatedAt",
    // ],
    // ArchivedGoalieDayStatLine: [  // Disabled for performance
    //   "id",
    //   "originalId",
    //   "seasonId",
    //   "gshlTeamId",
    //   "playerId",
    //   "weekId",
    //   "date",
    //   "nhlPos",
    //   "posGroup",
    //   "nhlTeam",
    //   "fullPos",
    //   "bestPos",
    //   "dailyPos",
    //   "opp",
    //   "score",
    //   "IR",
    //   "IRplus",
    //   "GP",
    //   "MG",
    //   "GS",
    //   "W",
    //   "GA",
    //   "GAA",
    //   "SV",
    //   "SA",
    //   "SVP",
    //   "SO",
    //   "TOI",
    //   "ADD",
    //   "Rating",
    //   "MS",
    //   "BS",
    //   "archivedDate",
    //   "archiveReason",
    //   "originalCreatedAt",
    //   "originalUpdatedAt",
    //   "createdAt",
    //   "updatedAt",
    // ],
  } as const,
};

// Type definitions
type DatabaseValue =
  | string
  | number
  | boolean
  | Date
  | null
  | undefined
  | unknown[]
  | Record<string, unknown>;

export type DatabaseRecord = Record<string, DatabaseValue>;

// Type-safe helper to convert database data to sheet row
export function convertModelToRow<T extends DatabaseRecord>(
  data: T,
  columns: readonly string[],
): (string | number | boolean)[] {
  return columns.map((column) => {
    const value = data[column];

    // Handle special data types
    if (value === null || value === undefined) {
      return "";
    }

    if (Array.isArray(value)) {
      return JSON.stringify(value);
    }

    if (value instanceof Date) {
      return value.toISOString();
    }

    if (typeof value === "boolean") {
      return value;
    }

    if (typeof value === "object" && value !== null) {
      return JSON.stringify(value);
    }

    return String(value);
  });
}

// Type-safe helper to convert sheet row to database data
export function convertRowToModel<T extends DatabaseRecord>(
  row: (string | number | boolean | null)[],
  columns: readonly string[],
): T {
  const result: Record<string, DatabaseValue> = {};

  columns.forEach((column, index) => {
    const value = row[index];

    if (value === "" || value === null || value === undefined) {
      result[column] = null;
      return;
    }

    // Handle special conversions based on column name patterns
    if (column === "id" || column.endsWith("Id")) {
      result[column] = parseInt(String(value), 10);
    } else if (column.endsWith("At")) {
      result[column] = new Date(String(value));
    } else if (
      column === "nhlPos" ||
      column === "nhlTeam" ||
      column === "categories" ||
      column === "rosterSpots"
    ) {
      try {
        result[column] = JSON.parse(String(value)) as unknown[];
      } catch {
        result[column] = [String(value)];
      }
    } else if (typeof value === "string" && value.toLowerCase() === "true") {
      result[column] = true;
    } else if (typeof value === "string" && value.toLowerCase() === "false") {
      result[column] = false;
    } else if (
      typeof value === "string" &&
      !isNaN(Number(value)) &&
      value !== ""
    ) {
      // Handle numeric values
      const numValue = Number(value);
      result[column] =
        numValue % 1 === 0 ? parseInt(value, 10) : parseFloat(value);
    } else {
      result[column] = value;
    }
  });

  return result as T;
}
