export const env = {
  NODE_ENV: process.env.NODE_ENV ?? "development",
  GSHL_DATA_BACKEND: process.env.GSHL_DATA_BACKEND ?? "sheets",
  USE_GOOGLE_SHEETS: process.env.USE_GOOGLE_SHEETS ?? "true",
  GOOGLE_SERVICE_ACCOUNT_KEY_FILE: process.env.GOOGLE_SERVICE_ACCOUNT_KEY_FILE,
  GOOGLE_SERVICE_ACCOUNT_KEY: process.env.GOOGLE_SERVICE_ACCOUNT_KEY,
  GOOGLE_APPS_SCRIPT_ID: process.env.GOOGLE_APPS_SCRIPT_ID,
  GOOGLE_APPS_SCRIPT_ACCESS_TOKEN: process.env.GOOGLE_APPS_SCRIPT_ACCESS_TOKEN,
  NEXT_PUBLIC_CONVEX_URL: process.env.NEXT_PUBLIC_CONVEX_URL,
  CONVEX_DEPLOYMENT: process.env.CONVEX_DEPLOYMENT,
  CONVEX_DEPLOY_KEY: process.env.CONVEX_DEPLOY_KEY,
};
