export const env = {
  NODE_ENV: process.env.NODE_ENV ?? "development",
  USE_GOOGLE_SHEETS: process.env.USE_GOOGLE_SHEETS ?? "true",
  GOOGLE_SERVICE_ACCOUNT_KEY_FILE:
    process.env.GOOGLE_SERVICE_ACCOUNT_KEY_FILE,
  GOOGLE_SERVICE_ACCOUNT_KEY: process.env.GOOGLE_SERVICE_ACCOUNT_KEY,
  GOOGLE_APPS_SCRIPT_ID: process.env.GOOGLE_APPS_SCRIPT_ID,
  GOOGLE_APPS_SCRIPT_ACCESS_TOKEN:
    process.env.GOOGLE_APPS_SCRIPT_ACCESS_TOKEN,
};
