export const CONFERENCE_LEAD_REPORTERS_BY_LEGACY_ID: Record<string, string> = {
  "1": "Bruce McAllister",
  "2": "Ken Brodie",
};

export const FRANCHISE_BEAT_WRITERS_BY_LEGACY_ID: Record<string, string> = {
  "1": "Gord McKenzie",
  "2": "Darren Whitmore",
  "3": "Scott Callahan",
  "4": "Mike Bouchard",
  "5": "Trevor McLean",
  "6": "Ryan O'Rourke",
  "7": "Brent Hollister",
  "8": "Colin MacDougall",
  "9": "Jason Pritchard",
  "10": "Mark Delaney",
  "11": "Tyler Beaulieu",
  "12": "Craig Henshaw",
  "13": "Adam Kavanagh",
  "14": "Luke Ferris",
  "15": "Matt Donnelly",
  "16": "Sean Mercer",
  "17": "Kyle Duguay",
  "18": "Eric Sanderson",
  "19": "Brad Kovacs",
  "20": "Jeff Leduc",
  "21": "Peter Langford",
  "22": "Nick Gauthier",
  "23": "Owen Rielly",
  "24": "Chris Vandermeer",
  "25": "Daniel Forsberg",
  "26": "Anders Lindholm",
  "27": "Henrik Nyström",
  "28": "Mats Ekberg",
  "29": "Jonas Håkansson",
  "30": "Erik Lundqvist",
  "31": "Mikko Laine",
  "32": "Antti Salonen",
  "33": "Jari Nieminen",
  "34": "Teemu Korpela",
  "35": "Pavel Horák",
  "36": "Marek Novotný",
  "37": "Jan Kowalski",
  "38": "Tomasz Zieliński",
  "39": "Lukas Gruber",
  "40": "Stefan Bauer",
  "41": "Jake Miller",
  "42": "Connor Hayes",
  "43": "Doug Campbell",
  "44": "Rob Sinclair",
};
